/** Screen layout metrics (393pt mobile frame) */
export const layout = {
  screenPadding: 16,
  locationHeaderHeight: 61,
  categoryRowHeight: 72,
  filterRowHeight: 54,
  promoHeight: 160,
  promoWidth: 330,
  promoGap: 16,
  promoRadius: 16,
  promoContentPadding: 20,
  promoButtonWidth: 104,
  promoButtonHeight: 28,
  promoButtonRadius: 4,
  promoPaginationHeight: 14,
  promoPaginationActiveWidth: 46,
  promoPaginationInactiveSize: 8,
  sectionHeaderHeight: 32,
  sectionGap: 24,
  cardGap: 8,
  largeCardImageHeight: 180,
  largeCardRadius: 8,
  smallCardWidth: 260,
  smallCardHeight: 184,
  smallCardImageHeight: 130,
  smallCardGap: 12,
  pillHeight: 36,
  pillRadius: 999,
  tabBarHeight: 56,
  tabIconSize: 20,
  buttonRadius: 4,
  inputHeight: 48,
  inputRadius: 4,
  inputPaddingH: 15,
  /** Auth screens (Log in / Sign up) — node 537:38606 */
  authContentTop: 20,
  authSocialGap: 16,
  authSectionGap: 24,
  authFieldLabelGap: 16,
  authSignupFieldLabelGap: 12,
  authNameColumnGap: 17,
  authTermsTopGap: 16,
  socialButtonHeight: 44,
  socialIconSize: 32,
  /** Search tab — Screen/ Search/ 1 */
  searchHeaderHeight: 128,
  searchHeaderCompactHeight: 64,
  searchListItemHeight: 48,
  searchResultItemHeight: 64,
  searchSectionGap: 32,
  searchTitleListGap: 24,
  /** Restaurant page — Screen/ Recipe/ Restaurant page/ 01 */
  restaurantCoverHeight: 212,
  restaurantMenuItemHeight: 106,
  /** Orders list row */
  orderRowHeight: 108,
} as const;

export type LayoutToken = typeof layout;
